path_to_app = "/etc/capsule/timelapse_trip"
path_to_timelapse_tmp = "/tmp/timelapse_trip"
path_to_current_results = "/mnt/data/shares/data/timelapses"
path_to_conf = "/etc/capsule/timelapse_trip/config.yaml"
path_to_services = "/etc/systemd/system/timelapse_trip.service"